/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../api/axios";
import { useAuth } from "../auth/AuthContext";
import "../App.css";

export default function EventDetails() {
  const { id } = useParams(); const { user } = useAuth(); const [event, setEvent] = useState(null); const [gifts, setGifts] = useState([]); const [newGift, setNewGift] = useState({ name: "", description: "", image: null }); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const fetchGifts = async () => { const res = await api.get(`/gifts/event/${id}`); setGifts(res.data); }; const fetchEvent = async () => { const res = await api.get(`/events/${id}`); setEvent(res.data); };
  useEffect(() => { Promise.all([fetchEvent(), fetchGifts()]).catch(() => setError("We couldn't load this event.")).finally(() => setLoading(false)); }, [id]);
  const isOrganizer = event?.organizer?._id ? event.organizer._id === user._id : event?.organizer === user._id;
  const createGift = async (e) => { e.preventDefault(); if (!newGift.name.trim()) return; try { const data = new FormData(); data.append("name", newGift.name); data.append("description", newGift.description); data.append("event", id); if (newGift.image) data.append("image", newGift.image); await api.post("/gifts", data, { headers: { "Content-Type": "multipart/form-data" } }); await fetchGifts(); setNewGift({ name: "", description: "", image: null }); setError(""); } catch (err) { setError(err.response?.data?.message || "We couldn't add that gift."); } };
  const action = async (url, method = "post") => { try { await api[method](url); await fetchGifts(); } catch (err) { setError(err.response?.data?.message || "We couldn't update that gift."); } };
  if (loading) return <div className="loading-state">Loading event details…</div>; if (!event) return <main className="page-wrap"><div className="empty-state"><h3>Event not found</h3><p>This celebration may have been removed.</p><Link className="text-link" to="/events">Return to my events</Link></div></main>;
  const date = event.date ? new Date(event.date).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" }) : "Date to be decided";
  return <main className="page-wrap"><Link to={isOrganizer ? "/events" : "/feed"} className="text-link text-sm">← Back to events</Link><header className="page-header mt-5"><div><p className="eyebrow">{isOrganizer ? "Your celebration" : "Friend’s celebration"}</p><h1 className="page-title">{event.title}</h1><p className="page-subtitle">{event.description || "A thoughtful celebration, planned together."}</p><p className="metadata"><span aria-hidden="true">◷</span>{date}</p></div><span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-bold text-violet-800">{gifts.length} {gifts.length === 1 ? "gift" : "gifts"}</span></header>
    <section><div className="mb-4"><h2 className="section-title">Gift wishlist</h2><p className="section-description">{isOrganizer ? "Add ideas to help friends choose something you’ll love." : "Choose a gift to make this celebration extra special."}</p></div>{gifts.length === 0 ? <div className="empty-state"><div className="empty-icon">🎁</div><h3>No gifts have been added yet</h3><p>{isOrganizer ? "Use the form below to start your wishlist." : "Check back soon for gift ideas."}</p></div> : <div className="event-grid">{gifts.map((gift) => { const pledgedByMe = gift.pledgedBy === user._id; return <article key={gift._id} className="surface gift-card">{gift.imageUrl && <img src={gift.imageUrl} alt={gift.name} className="mb-4 h-44 w-full rounded-xl object-cover" />}<h3 className="card-title">{gift.name}</h3>{gift.description && <p className="card-copy">{gift.description}</p>}<p className={`mt-3 inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${gift.pledgedBy ? "bg-violet-100 text-violet-800" : "bg-emerald-50 text-emerald-700"}`}>{gift.pledgedBy ? (pledgedByMe ? "You’ve claimed this" : "Already claimed") : "Available"}</p><div className="card-actions">{!isOrganizer && !gift.pledgedBy && <button onClick={() => action(`/gifts/${gift._id}/pledge`)} className="btn btn-primary">Claim gift</button>}{!isOrganizer && pledgedByMe && <button onClick={() => action(`/gifts/${gift._id}/unpledge`)} className="btn btn-secondary">Release gift</button>}{isOrganizer && <button onClick={() => action(`/gifts/${gift._id}`, "delete")} className="btn btn-danger">Remove</button>}</div></article>; })}</div>}</section>
    {isOrganizer && <form onSubmit={createGift} className="surface form-card mt-10"><h2 className="section-title">Add a gift idea</h2><p className="section-description">An image gives your friends a clearer idea of what you have in mind.</p><div className="grid gap-4 md:grid-cols-2"><div><label className="field-label" htmlFor="gift-name">Gift name</label><input id="gift-name" className="field-input" value={newGift.name} onChange={(e) => setNewGift({ ...newGift, name: e.target.value })} placeholder="e.g. Ceramic pour-over set" required /></div><div><label className="field-label" htmlFor="gift-image">Image <span className="font-normal text-slate-400">(optional)</span></label><input id="gift-image" className="field-input" type="file" accept="image/png,image/jpeg" onChange={(e) => setNewGift({ ...newGift, image: e.target.files[0] })} /></div><div className="md:col-span-2"><label className="field-label" htmlFor="gift-description">Description <span className="font-normal text-slate-400">(optional)</span></label><textarea id="gift-description" className="field-textarea" value={newGift.description} onChange={(e) => setNewGift({ ...newGift, description: e.target.value })} placeholder="Share a colour, size, link, or other useful details…" /></div></div><div className="mt-4"><button className="btn btn-primary">Add to wishlist</button></div></form>}{error && <p className="notice notice-error">{error}</p>}
  </main>;
}
