/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import api from "../api/axios";
import "../App.css";

export default function Friends() {
  const [email, setEmail] = useState(""); const [requests, setRequests] = useState([]); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const loadRequests = async () => { try { const res = await api.get("/friends/requests"); setRequests(res.data); } catch { setError("We couldn't load incoming requests."); } };
  useEffect(() => { loadRequests(); }, []);
  const sendInvite = async (e) => { e.preventDefault(); setMessage(""); setError(""); try { await api.post("/friends/invite", { email }); setMessage("Invitation sent — we’ll let you know when they accept."); setEmail(""); } catch (err) { setError(err.response?.data?.message || "We couldn't send that invitation."); } };
  const respond = async (id, action) => { try { await api.post(`/friends/${action}/${id}`); await loadRequests(); } catch { setError("We couldn't update this request."); } };
  return <main className="page-wrap"><header className="page-header"><div><p className="eyebrow">Your circle</p><h1 className="page-title">Friends</h1><p className="page-subtitle">Bring your people together for every celebration.</p></div></header><form onSubmit={sendInvite} className="surface form-card"><h2 className="section-title">Invite someone to GiftWise</h2><p className="section-description">Enter their account email to send a friend request.</p><div className="flex flex-col gap-3 sm:flex-row"><input type="email" className="field-input flex-1" placeholder="friend@example.com" value={email} onChange={(e) => setEmail(e.target.value)} required /><button type="submit" className="btn btn-primary">Send invitation</button></div>{message && <p className="notice notice-success">{message}</p>}{error && <p className="notice notice-error">{error}</p>}</form><section><div className="mb-4 flex items-center justify-between"><h2 className="section-title">Incoming requests</h2><span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-bold text-violet-800">{requests.length} pending</span></div>{requests.length === 0 ? <div className="empty-state"><div className="empty-icon">♥</div><h3>No requests waiting</h3><p>When someone invites you, their request will appear here.</p></div> : <div className="event-grid">{requests.map((request) => <article key={request._id} className="surface event-card"><h3 className="card-title">{request.sender.name}</h3><p className="card-copy">{request.sender.email}</p><div className="card-actions"><button onClick={() => respond(request._id, "accept")} className="btn btn-primary">Accept</button><button onClick={() => respond(request._id, "reject")} className="btn btn-secondary">Decline</button></div></article>)}</div>}</section></main>;
}
