import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import "../App.css";

export default function Login() {
  const { login } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ email: "", password: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (e) => { e.preventDefault(); setLoading(true); setError(""); try { await login(form.email, form.password); navigate("/events"); } catch (err) { setError(err.response?.data?.message || "We couldn't log you in. Check your details and try again."); } finally { setLoading(false); } };
  return <div className="auth-page"><aside className="auth-showcase"><span className="showcase-pill">A more thoughtful way to celebrate</span><div><h2>Every great gift starts with a little thought.</h2><p>Plan celebrations, share ideas, and let friends coordinate the gifts that matter.</p></div><span className="text-sm text-violet-100">✦ GiftWise</span></aside><main className="auth-panel"><div className="surface auth-card"><Link to="/login" className="brand"><span className="brand-mark">✦</span>GiftWise</Link><h1>Welcome back</h1><p>Log in to continue planning memorable moments.</p>{error && <p className="notice notice-error">{error}</p>}<form onSubmit={submit} className="mt-6 space-y-4"><div><label className="field-label" htmlFor="email">Email address</label><input id="email" className="field-input" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" required /></div><div><label className="field-label" htmlFor="password">Password</label><input id="password" className="field-input" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Your password" required /></div><button className="btn btn-primary mt-2 w-full" disabled={loading}>{loading ? "Logging in…" : "Log in"}</button></form><p className="auth-footer">New to GiftWise? <Link className="text-link" to="/register">Create an account</Link></p></div></main></div>;
}
