import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import "../App.css";

export default function Register() {
  const { register } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: "", email: "", password: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (e) => { e.preventDefault(); setLoading(true); setError(""); try { await register(form.name, form.email, form.password); navigate("/login"); } catch (err) { setError(err.response?.data?.message || "We couldn't create your account. Please try again."); } finally { setLoading(false); } };
  return <div className="auth-page"><aside className="auth-showcase"><span className="showcase-pill">Your celebrations, beautifully organised</span><div><h2>Make every occasion feel personal.</h2><p>Keep gift ideas in one place and make it simple for friends to celebrate with you.</p></div><span className="text-sm text-violet-100">✦ GiftWise</span></aside><main className="auth-panel"><div className="surface auth-card"><Link to="/login" className="brand"><span className="brand-mark">✦</span>GiftWise</Link><h1>Create your account</h1><p>Start planning celebrations with your favourite people.</p>{error && <p className="notice notice-error">{error}</p>}<form onSubmit={submit} className="mt-6 space-y-4"><div><label className="field-label" htmlFor="name">Your name</label><input id="name" className="field-input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Alex Morgan" required /></div><div><label className="field-label" htmlFor="email">Email address</label><input id="email" className="field-input" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" required /></div><div><label className="field-label" htmlFor="password">Password</label><input id="password" className="field-input" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Create a password" required /></div><button className="btn btn-primary mt-2 w-full" disabled={loading}>{loading ? "Creating account…" : "Create account"}</button></form><p className="auth-footer">Already have an account? <Link className="text-link" to="/login">Log in</Link></p></div></main></div>;
}
